### ISSUE TITLE
[Known Issue] Versão de treinamento não funciona

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/e-SUS-PEC#11]
Já reportado à equipe de suporte.

Ao executar o comando 

```sh
java -jar eSUS-AB-PEC-5.2.28-Linux64.jar -console -url="jdbc:postgresql://psql:5432/esus" -username postgres -password esus -treinamento
``` 

no ambiente do container `ubuntu 20.04` o terminal retorna o erro:

![image](https://github.com/filiperochalopes/e-SUS-PEC/assets/34348097/ee8a8376-fb64-42aa-98ed-602b0f64e3d7)

Ao executar sem a opção de treinamento:

![image](https://github.com/filiperochalopes/e-SUS-PEC/assets/34348097/ce972a63-fae2-4fba-84b1-999e2edbfde6)

...

![image](https://github.com/filiperochalopes/e-SUS-PEC/assets/34348097/128e8555-8e36-47d4-acbe-6502d01f36e4)

...

![image](https://github.com/filiperochalopes/e-SUS-PEC/assets/34348097/038d3e7c-7bf5-44b9-ad24-796354be13da)

**Comment by filiperochalopes** [comment]
Resposta da Universidade que dá suporte ao sistema (Java 8, Ubuntu 22.04.4 LTS):

![image](https://github.com/filiperochalopes/e-SUS-PEC/assets/34348097/424027c4-aadd-4441-a516-f009b005471d)

Utilizar debian 11 pode ser uma saída, já que ela facilita a instalação de java:

```sh
yarn
sudo apt-get update
java --version
sudo apt-get install openjdk-17-jre openjdk-17-jdk
echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 export JAVA_HOME export PATH=$PATH:$JAVA_HOME" >> ~/.bashrc
```

**Comment by ErickSousa312** [comment]
Esse problema ja foi resolvido ??

**Comment by filiperochalopes** [comment]
Ainda não, não estamos dando prioridade a isso no momento, talvez em breve,
junto ou logo após resolvermos a questão do ssl. Tem interesse na
funcionalidade?

Em sáb., 7 de set. de 2024 às 18:44, Erik sales ***@***.***>
escreveu:

**Comment by ErickSousa312** [comment]
Opa tenho sim, aonde eu trabalho (secreataria de saude da minha cidade) queriamos colocar o Esus de treinamento no docker porem vimos ai que tem problema, tentei por outros meios ainda usando o docker mas sempre dava problema.

**Comment by filiperochalopes** [comment]
@ErickSousa312 entra em contato comigo em https://wa.me/5571986056232 para ver como conseguimos resolver mais rápido

**Comment by filiperochalopes** [comment]
@ErickSousa312 @tifilipebr Versão de Treinamento está funcionando! 🥳
